modified:   .circleci/config.yml 	modified:   Dockerfile_mbtci_java17

diff --git a/Dockerfile_mbtci_java17 b/Dockerfile_mbtci_java17
--- a/Dockerfile_mbtci_java17
+++ b/Dockerfile_mbtci_java17
@@ -1,39 +1,57 @@
 FROM sapmachine:17
 
 # Build time arguments
-ARG MTA_USER_HOME=/home/mta
+ARG USER="mta"
+ARG USER_HOME_DIR=/home/mta
+
 ARG MBT_VERSION=1.2.71
 ARG GO_VERSION=1.15.6
 # node version as found in https://nodejs.org/dist/ e.g: "v16.15.0"
 ARG NODE_VERSION=NODE_VERSION_TEMPLATE
-ARG MAVEN_VERSION=3.6.3
+#ARG MAVEN_VERSION=3.6.3
 
 # Environment variables
 ENV PYTHON /usr/bin/python3
-ENV M2_HOME=/opt/maven/apache-maven-${MAVEN_VERSION}
+#ENV M2_HOME=/opt/maven/apache-maven-${MAVEN_VERSION}
 ENV GOPATH /go
 ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
 ENV CGO_ENABLED=0
 ENV GOOS=linux
 ENV DEBIAN_FRONTEND=noninteractive
 
+RUN set -ex \
+  && apt-get update \
+  && apt-get install -y openssl --no-install-recommends \
+  && rm -rf /var/lib/apt/lists/* \
+   # smoke test
+  && openssl version \
+  && useradd --home-dir ${USER_HOME_DIR} \
+            --create-home \
+            --shell /bin/bash \
+            --user-group \
+            --uid 1000 \
+            --comment 'Cloud MTA Build Tool' \
+            --password "$(echo weUseMta | openssl passwd -1 -stdin)" ${USER} \
+  # allow anybody to write into the image user home directory
+  && chmod a+w ${USER_HOME_DIR}
+
+# # Download required env tools (commented by young-yang03)
+# RUN apt-get update && \
+#     apt-get install --yes --no-install-recommends \
+# 		ca-certificates \
+# 		git \
+# 		curl && \
+
+#     # Change security level as the SAP npm repo doesnt support buster new security upgrade
+#     # the default configuration for OpenSSL in Buster explicitly requires using more secure ciphers and protocols,
+#     # and the server running at http://npm.sap.com/ is running software configured to only provide insecure, older ciphers.
+#     # This causes SSL connections using OpenSSL from a Buster based installation to fail
+#     # Should be remove once SAP npm repo will patch the security level
+#     # see - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912759
+#     sed -i -E 's/(CipherString\s*=\s*DEFAULT@SECLEVEL=)2/\11/' /etc/ssl/openssl.cnf
+
 ADD http://aia.pki.co.sap.com/aia/SAP%20Global%20Root%20CA.crt \
     /etc/ssl/certs/SAP_Global_Root_CA.crt
-
-# Download required env tools
-RUN apt-get update && \
-    apt-get install --yes --no-install-recommends \
-		ca-certificates \
-		git \
-		curl && \
-
-    # Change security level as the SAP npm repo doesnt support buster new security upgrade
-    # the default configuration for OpenSSL in Buster explicitly requires using more secure ciphers and protocols,
-    # and the server running at http://npm.sap.com/ is running software configured to only provide insecure, older ciphers.
-    # This causes SSL connections using OpenSSL from a Buster based installation to fail
-    # Should be remove once SAP npm repo will patch the security level
-    # see - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912759
-    sed -i -E 's/(CipherString\s*=\s*DEFAULT@SECLEVEL=)2/\11/' /etc/ssl/openssl.cnf
 
 # install node
 RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
@@ -88,7 +106,7 @@ RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
     && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
     # smoke tests
     && node --version \
-    && npm --version \
+    && npm --version
 
 # install node (commented by young-yang03) 
 	# NODE_HOME=/opt/nodejs; mkdir -p ${NODE_HOME} && \
@@ -98,16 +116,32 @@ RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
     # ln -s "${NODE_HOME}/node-${NODE_VERSION}-linux-x64/bin/npm" /usr/local/bin/npm && \
     # ln -s "${NODE_HOME}/node-${NODE_VERSION}-linux-x64/bin/npx" /usr/local/bin/ && \
     # npm install --prefix /usr/local/ -g grunt-cli && \
-	
+
 # install ui5-cli temporay solution
-	npm install --prefix /usr/local/ -g @ui5/cli && \
+RUN	npm install --prefix /usr/local/ -g @ui5/cli
 
-# installing Golang
-	curl -O https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz && tar -xvf go${GO_VERSION}.linux-amd64.tar.gz && \
-    mv go /usr/local && \
-    mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH" && \
-    mkdir -p ${GOPATH}/src ${GOPATH}/bin
+# install ui5-cli temporay solution (commented by young-yang03) 
+	# npm install --prefix /usr/local/ -g @ui5/cli && \
 
+# install Golang
+RUN	set -ex \
+    && apt-get update \
+    && apt-get install -y ca-certificates curl --no-install-recommends \
+    && rm -rf /var/lib/apt/lists/* \
+    && curl -O https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz \
+    && tar -xvf go${GO_VERSION}.linux-amd64.tar.gz \
+    && mv go /usr/local \
+    && mkdir -p "$GOPATH/src" "$GOPATH/bin" \
+    && chmod -R 777 "$GOPATH" \
+    && mkdir -p ${GOPATH}/src ${GOPATH}/bin \
+    # smoke tests
+    && go version
+
+# installing Golang (commented by young-yang03) 
+    # curl -O https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz && tar -xvf go${GO_VERSION}.linux-amd64.tar.gz && \
+    # mv go /usr/local && \
+    # mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH" && \
+    # mkdir -p ${GOPATH}/src ${GOPATH}/bin && \
 
 # install maven
 ARG MAVEN_VERSION=3.8.6
@@ -136,7 +170,7 @@ RUN set -ex \
   && ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn \
   && apt-get remove --purge --autoremove -y ca-certificates curl gnupg dirmngr \
   # smoke test
-  && mvn --version \
+  && mvn --version
 
 # update maven home (commnet by young-yang)
 	# M2_BASE="$(dirname ${M2_HOME})" && \
@@ -146,33 +180,41 @@ RUN set -ex \
     # ln -s "${M2_HOME}/bin/mvn" /usr/local/bin/mvn && \
     # chmod --recursive a+w "${M2_HOME}"/conf/* && \
 
-# Download MBT
-	curl -L "https://github.com/young-yang03/cloud-mta-build-tool/releases/download/v${MBT_VERSION}/cloud-mta-build-tool_${MBT_VERSION}_Linux_amd64.tar.gz" | tar -zx -C /usr/local/bin && \
-    chown root:root /usr/local/bin/mbt && \ 
+# Install MBT
+RUN	set -ex \
+  && apt-get update \
+  && apt-get install -y ca-certificates curl --no-install-recommends \
+  && rm -rf /var/lib/apt/lists/* \
+  && curl -L "https://github.com/young-yang03/cloud-mta-build-tool/releases/download/v${MBT_VERSION}/cloud-mta-build-tool_${MBT_VERSION}_Linux_amd64.tar.gz" | tar -zx -C /usr/local/bin && \
+  && chown root:root /usr/local/bin/mbt \
+  # smoke test
+  && mbt --version \
 
-# handle users permission
-	useradd --home-dir "${MTA_USER_HOME}" \
-            --create-home \
-            --shell /bin/bash \
-            --user-group \
-            --uid 1000 \
-            --comment 'Cloud MTA Build Tool' \
-            --password "$(echo weUseMta |openssl passwd -1 -stdin)" mta && \
-# allow anybody to write into the images HOME
-    chmod a+w "${MTA_USER_HOME}" && \
+# Download MBT (commnet by young-yang)
+	# curl -L "https://github.com/young-yang03/cloud-mta-build-tool/releases/download/v${MBT_VERSION}/cloud-mta-build-tool_${MBT_VERSION}_Linux_amd64.tar.gz" | tar -zx -C /usr/local/bin && \
+    # chown root:root /usr/local/bin/mbt && \
 
-# Install essential build tools and python, required for building db modules
-	apt-get install --yes --no-install-recommends \
-		build-essential \
-        python2.7 \
-		python3 && \
-		
-# remove build env tools
-    apt-get remove --purge --autoremove --yes \
-		curl && \
+# Install essential build tools and python
+RUN set -ex \
+  && apt-get update \
+  && apt-get install -y ca-certificates build-essential python2.7 python3 --no-install-recommends \
+  && rm -rf /var/lib/apt/lists/* \
+  # smoke test
+  && python2.7 --version \
+  && python3 --version \
 
-    rm -rf /var/lib/apt/lists/*
+# # Install essential build tools and python, required for building db modules (commnet by young-yang)
+# 	apt-get install --yes --no-install-recommends \
+# 		build-essential \
+#       python2.7 \
+# 		python3 && \
 
-ENV PATH=$PATH:./node_modules/.bin HOME=${MTA_USER_HOME}
+# remove build env tools (commented by young-yang03) 
+    # apt-get remove --purge --autoremove --yes \
+	# 	curl && \
+
+    # rm -rf /var/lib/apt/lists/*
+
+ENV PATH=$PATH:./node_modules/.bin HOME=${USER_HOME_DIR}
 WORKDIR /project
-USER mta
+USER ${USER}
